# Test Normal model implementation

In [1]:
import numpy as np
from option_models import basket
from option_models import basket_Levy

In [14]:
### only run this when you changed the class definition
import imp
imp.reload(basket)

<module 'option_models.basket' from 'C:\\Users\\lantm\\Documents\\GitHub\\hw3-team_87\\option_models\\basket.py'>

In [2]:
# A trivial test case 1: 
# one asset have 100% weight (the others zero)
# the case should be equivalent to the BSM or Normal model price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.2
weights = np.array([1, 0, 0, 0])
divr = np.zeros(4)
intr = 0
cor_m = 0.8*np.identity(4) + 0.2*np.ones((4,4))
texp = 1
strike = 102

print(weights)

a=basket.basket_price_mc(strike, spot, vol, weights, texp, cor_m, bsm=True)
b=basket_Levy.basket_price_Levy(strike, spot, vol, weights, texp, cor_m)
print(a)
print(b)
# write your own normal model pricing here and compare
# do the similar for BSM model

[1 0 0 0]
7.11711843013
7.08449424783


In [3]:
# A trivial test case 2

# all assets almost perfectly correlated:
# the case should be equivalent to the BSM or Normal model price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.2
weights = np.ones(4) * 0.25
divr = np.zeros(4)
intr = 0
cor_m = 0.0001*np.identity(4) + 0.9999*np.ones((4,4))
texp = 1
strike = 102

print( cor_m )

a=basket.basket_price_mc(strike, spot, vol, weights, texp, cor_m, bsm=True)
b=basket_Levy.basket_price_Levy(strike, spot, vol, weights, texp, cor_m)
print(a)
print(b)
# write your own normal model pricing here and compare
# do the similar for BSM model

[[ 1.      0.9999  0.9999  0.9999]
 [ 0.9999  1.      0.9999  0.9999]
 [ 0.9999  0.9999  1.      0.9999]
 [ 0.9999  0.9999  0.9999  1.    ]]
7.06142304636
7.0841950358


In [4]:
# A test set for spread option

spot = np.array([100, 96])
vol = np.array([0.2, 0.1])
weights = np.array([1, -1])
divr = np.array([1, 1])*0.05
intr = 0.1
cor_m = np.array([[1, 0.5], [0.5, 1]])
texp = 1
strike = 0
price = 8.5132252

In [5]:
# MC price based on normal model
# make sure that the prices are similar\

np.random.seed(123456)
a=basket.basket_price_mc(strike, spot, vol, weights, texp, cor_m, intr=intr, divr=divr, bsm=True)
b=basket_Levy.basket_price_Levy(strike, spot, vol, weights, texp, cor_m, intr=intr, divr=divr)
print(a)
print(b)

8.5253941742
3.804917698


C:\Users\lantm\Documents\project\option_models\basket_Levy.py:25: RuntimeWarning: divide by zero encountered in log
  d1 = (m - np.log(strike) + v2) / v


In [6]:
# A test set for basket option
spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.ones(4) * 0.25
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5*np.ones((4,4))
texp = 5
strike = 100
price = 28.0073695

In [7]:
# MC price based on normal model
# make sure that the prices are similar

a=basket.basket_price_mc(strike, spot, vol, weights, texp, cor_m, bsm=True)
b=basket_Levy.basket_price_Levy(strike, spot, vol, weights, texp, cor_m)
print(a)
print(b)

27.1834537155
28.0519662142
